### ISSUE TITLE
Make Ansible Modules Idempotent

### ISSUE THREAD

**Issue by c0dyhi11** [PureStorage-OpenConnect/ansible-playbook-examples#3]
Every time I run the purefa_host module it says "Changed" even though no changes were made. Can you please make this idempotent? I would like to be able to run 1x Playbook and have it configure my entire array.  And only items that are actually changed should be marked as changed.

**Comment by sdodsley** [comment]
@c0dyhi11 can you detail the actual play that is causing this to happen? Also, confirm the version of ansible you are using...

**Comment by sdodsley** [comment]
Looks like a bug crept in in 2.8.3. This is fixed using https://github.com/ansible/ansible/pull/60367
