### ISSUE TITLE
The error was: NameError: name 'flashblade' is not defined

### ISSUE THREAD

**Issue by assaffeuerstein** [PureStorage-OpenConnect/ansible-playbook-examples#56]
When running ansible to set user policy:

    - name: Set user policy
      purefb_userpolicy:
        name: "{{ fb_user_name }}"
        account: "{{ fb_account_name }}"
        policy:
          - pure:policy/bucket-info
          - pure:policy/bucket-list
          - pure:policy/object-delete
          - pure:policy/object-list
          - pure:policy/object-read
          - pure:policy/object-write
        fb_url: "{{ fb_url }}"
        api_token: "{{ api_token }}"
        state: present

This error comes up: "The error was: NameError: name 'flashblade' is not defined"

Full log here:

TASK [Set user policy] *********************************************************************************************************************************************************************************************************************************************************
task path: /Users/user/Desktop/Git/StorageAdmin/ansible/createAccountAndBucket.yml:31
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/user/.ansible/tmp `"&& mkdir "` echo /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600 `" && echo ansible-tmp-1663231784.374453-88058-237659549406600="` echo /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600 `" ) && sleep 0'
Using module file /Users/user/.ansible/collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_userpolicy.py
<127.0.0.1> PUT /Users/user/.ansible/tmp/ansible-local-88055jx3o0_5b/tmp5nvobtuc TO /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/ /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.purestorage.flashblade.plugins.modules.purefb_userpolicy', init_globals=dict(_module_fqn='ansible_collections.purestorage.flashblade.plugins.modules.purefb_userpolicy', _modlib_path=modlib_path),
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/dg/3wffd1js285br3vdnr0jz7vr0000gp/T/ansible_purefb_userpolicy_payload_fm1daj9x/ansible_purefb_userpolicy_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_userpolicy.py", line 269, in <module>
  File "/var/folders/dg/3wffd1js285br3vdnr0jz7vr0000gp/T/ansible_purefb_userpolicy_payload_fm1daj9x/ansible_purefb_userpolicy_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_userpolicy.py", line 237, in main
  File "/var/folders/dg/3wffd1js285br3vdnr0jz7vr0000gp/T/ansible_purefb_userpolicy_payload_fm1daj9x/ansible_purefb_userpolicy_payload.zip/ansible_collections/purestorage/flashblade/plugins/module_utils/purefb.py", line 114, in get_system
NameError: name 'flashblade' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/user/.ansible/tmp/ansible-tmp-1663231784.374453-88058-237659549406600/AnsiballZ_purefb_userpolicy.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flashblade.plugins.modules.purefb_userpolicy', init_globals=dict(_module_fqn='ansible_collections.purestorage.flashblade.plugins.modules.purefb_userpolicy', _modlib_path=modlib_path),\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/dg/3wffd1js285br3vdnr0jz7vr0000gp/T/ansible_purefb_userpolicy_payload_fm1daj9x/ansible_purefb_userpolicy_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_userpolicy.py\", line 269, in <module>\n  File \"/var/folders/dg/3wffd1js285br3vdnr0jz7vr0000gp/T/ansible_purefb_userpolicy_payload_fm1daj9x/ansible_purefb_userpolicy_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_userpolicy.py\", line 237, in main\n  File \"/var/folders/dg/3wffd1js285br3vdnr0jz7vr0000gp/T/ansible_purefb_userpolicy_payload_fm1daj9x/ansible_purefb_userpolicy_payload.zip/ansible_collections/purestorage/flashblade/plugins/module_utils/purefb.py\", line 114, in get_system\nNameError: name 'flashblade' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by hanej** [comment]
I'm having the same problem.  I'm getting `NameError: name 'flashblade' is not defined`.

**Comment by hanej** [comment]
Installing `py-pure-client` gets past that error

**Comment by sdodsley** [comment]
`py-pure-client` is a prerequisite for the FlashBlade Ansible collections.  https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/blob/master/README.md

**Comment by bschonec** [comment]
This requirement is not specified at the Ansible collections site:  https://docs.ansible.com/ansible/latest/collections/purestorage/flashblade/index.html

**Comment by sdodsley** [comment]
@bschonec there is no requirement to list requirements in the Ansible Galaxy page for a Collection. In fact I think that that page is auto generated by Ansible. However, in the Red Hat Automation Hub the requirements are listed: https://console.redhat.com/ansible/automation-hub/repo/published/purestorage/flashblade/docs/
