### ISSUE TITLE
py-pure-client and/or requests are not installed. error in purefa_info.py

### ISSUE THREAD

**Issue by mudaliar** [PureStorage-OpenConnect/ansible-playbook-examples#57]
Hello,
I am getting an error in ansible
.ansible/collections/ansible_collections/purestorage/flasharray/plugins/module_utils/purefa.py module when the following ansible-playbook is run

> - hosts: localhost
>   gather_facts: true
>   collections:
>   - purestorage.flasharray
>   vars:
>     src_fa_url: <renamed-pure_name>
>     src_api_token: <hidden>
>   tasks:
>   - name: Get source FlashArray info
>     purefa_info:
>       gather_subset:
>       - minimum
>       - network
>       - interfaces
>       fa_url: "{{ src_fa_url }}"
>       api_token: "{{ src_api_token }}"
>     register: src_array_info

The code is breaking in “def get_system(module):” function in purefa.py
The following code runs fine with PurityOS 5.3.12 but gives an error in 6.2.6 Is there any quick fix for this?

Flasharray collection is
VERSION = 1.4
USER_AGENT_BASE = “Ansible” 

Error message with -vvv option

> The full traceback is:
> WARNING: The below traceback may *not* be related to the actual failure.
>   File "/tmp/ansible_purefa_info_payload_JB8L3X/ansible_purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 442, in <module>
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
>             "fa_url": "<renamed>",
>             "gather_subset": [
>                 "minimum",
>                 "network",
>                 "interfaces"
>             ]
>         }
>     },
>     "msg": "py-pure-client and/or requests are not installed."
> }

**Comment by sdodsley** [comment]
These are required packages for the Pure Ansible modules.

Please install on the host running the playbooks
